### ISSUE TITLE
change { ?o ?p <s>. } to { ?s ?p <e>. } or { ?s ?p <r>. }

### ISSUE THREAD

**Issue by elf-pavlik** [HydraCG/Specifications#105]
Reading [this section](https://github.com/HydraCG/Specifications/blob/b8fb55334096aa1f917e3474fd4ae31875492cc1/spec/latest/linked-data-fragments/index.html#L574-L578) of Linked Data Fragments spec
> The selector takes a single entity (subject) as argument, and matches triples that are related to this entity. 
The precise functional definition of the selector is implementation-specific, but it usually contains those triples that match the triple pattern { &lt;s&gt; ?p ?o. } and possibly triples matching { ?o ?p &lt;s&gt;. }, with &lt;s&gt; the chosen entity argument.

I understand that we want to select all triples which have given entity/resource as subject or object. Maybe alternatives I suggest below would use *?s ?p ?o* in more consistent way? In above the entity appears on object position and selector uses *?o* for subject, which I find a bit confusing.

"The precise functional definition of the selector is implementation-specific, but it usually contains those triples that match the triple pattern { &lt;e&gt; ?p ?o. } and possibly triples matching { ?s ?p &lt;e&gt;. }, with &lt;e&gt; the chosen entity argument."

While *s* suggests *subject*, *e* would stand for *entity* or possibly *r* could stand for *resource*

"The precise functional definition of the selector is implementation-specific, but it usually contains those triples that match the triple pattern { &lt;r&gt; ?p ?o. } and possibly triples matching { ?s ?p &lt;r&gt;. }, with &lt;r&gt; the chosen entity argument."

**Comment by akuckartz** [comment]
:+1: Good catch

**Comment by RubenVerborgh** [comment]
I actually used `<s>` on purpose to mean the _subject_ of the page, but I don't really mind either way. Maybe we could just call it `<entity>` then to avoid cryptic abbreviations.

**Comment by elf-pavlik** [comment]
:+1: `<entity>` and leaving *subject* for the subject of a triple

"The selector takes a single entity (primary topic of a document) as argument, and matches triples that are related to this entity. 
The precise functional definition of the selector is implementation-specific, but it usually contains those triples that match the triple pattern `{ <entity> ?p ?o. }` and possibly triples matching `{ ?s ?p <entity>. }`, with `<enity>` the chosen entity argument.

Not sure if worth mentioning any of those:
* http://xmlns.com/foaf/spec/#term_primaryTopic
* https://schema.org/mainEntity

**Comment by lanthaler** [comment]
+1 to entity
