### ISSUE TITLE
Hydra console: Label does not allow spaces

### ISSUE THREAD

**Issue by dtabakov** [HydraCG/Specifications#107]
I am writing a prototype for a Web API using Hydra. The Hydra Console fails to parse the ApiDocumentation whenever the Entry Point's "label" property contains spaces. In Markus' demo API he re-defines label as http://www.w3.org/2000/01/rdf-schema#label, which is the strategy we have adopted as well. To the best of my understanding, http://www.w3.org/2000/01/rdf-schema#label does allow spaces, therefore it seems that the issue is with the Console.

To repro: Change the label of the Entry Point in the Demo API (http://www.markus-lanthaler.com/hydra/api-demo/) from "EntryPoint" to "Entry contains spaces now Point".

**Comment by lanthaler** [comment]
This is the wrong repo. I created an issue in the correct one. Will follow up on it in the next couple of days. Do you have a public API which shows this error so that I could have a quick look?
