### ISSUE TITLE
readOnly vs readable

### ISSUE THREAD

**Issue by laszbalo** [HydraCG/Specifications#108]
I have found that there is naming mismatch between properties, like in the case of readOnly/readable property, inside the [published context file](https://www.w3.org/ns/hydra/core#) and the [latest draft](http://www.hydra-cg.com/spec/latest/core/#hydra:readable). What source is the normative one or which one should we use at this point?
Thanks,
Laszlo

**Comment by tpluscode** [comment]
The latest is `readable`/`writable` pair AFAICT, right?

What will it take to correct this in the context file?

**Comment by lanthaler** [comment]
This was an oversight from my side. Should be fixed now.
