### ISSUE TITLE
Add rdfs:isDefinedBy to all concepts and rdfs:seeAlso to vocabulary itself

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#12]
Every concept should link to the vocabulary and the vocabulary should link to the specification.

Perhaps also try what tools such as [Parrot](http://ontorule-project.eu/parrot) or [Specgen](http://github.com/specgen/specgen) can generate from the vocabulary definition.

**Comment by alien-mcl** [comment]
PR #226 addresses this issue. Closing
