### ISSUE TITLE
Class and Property should not have same name with just different capitalization 

### ISSUE THREAD

**Issue by elf-pavlik** [HydraCG/Specifications#133]
[Collection Design](https://www.w3.org/community/hydra/wiki/Collection_Design) currently uses property `hydra:collection` while `hydra:Collection` class already exists. For now I just capture this issue here not to side track in #132

**Comment by akuckartz** [comment]
Why not?

**Comment by tpluscode** [comment]
@lanthaler can you recall when this was discussed?

**Comment by lanthaler** [comment]
No, but I just found it :-) We discussed it in #28. Doesn't look like we ever finished that discussion though.

I'll close this as a duplicate of #28.
