### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by binhle410** [HydraCG/Specifications#153]
Is there yet a way to support i18n for a Resource?

**Comment by tpluscode** [comment]
I don't think it's been discussed... ever? Maybe a long time ago on the mailing list.

That said, you could get some quick win with RDF/JSON-LD support for multiple languages. Not sure what you are looking for, so your mileage may vary. 

I see this as two fold:

1. Translating the API Documentation, which should be simple enough to introduce by using languages in the descriptions
1. Having the API actually accept and work with multiple translations of resources. That is something that would require more though on how to tackle.

**Comment by lanthaler** [comment]
As Tomasz already mentioned, JSON-LD (and RDF in general) already has built-in support for multi-language strings. See http://www.w3.org/TR/json-ld/#string-internationalization

Is there anything else you are looking for @binhle410?

**Comment by tpluscode** [comment]
Closing as this seems answered and inactive

**Comment by alien-mcl** [comment]
OK. I believe it is resolved.
