### ISSUE TITLE
Inconsistent examples regarding pagination

### ISSUE THREAD

**Issue by paul** [HydraCG/Specifications#163]
The recently merged PR #159 added some new use case documents. The one for pagination embedded the `first`, `next`, etc links in the root of the collection document, while most other examples I've seen for pagination put them nested under a `view` key in a PartialCollectionView object. Which is the correct way? Should the examples at least be consistent?

https://github.com/HydraCG/Specifications/pull/159/files/1f4e6027d8885cdede04d300c5f5625aaf2c9fc3#diff-cc46591d2cf05932a3d79d5806d206dfR57

**Comment by lanthaler** [comment]
Thanks Paul. The `view` approach is the right one. It was introduced last year. Before that, pagination controls where directly associated to collections. I saw your offer to send a PR in your other comment. Would be fantastic if you find some time for that ;-)

**Comment by alien-mcl** [comment]
I've checked recently and found the pagination example seems to be correct now (see [3.2.pagination.md](https://github.com/HydraCG/cookbook/blob/master/drafts/3.2.pagination.md). I think this one can be closed.
