### ISSUE TITLE
hydra:Link should be an ObjectProperty

### ISSUE THREAD

**Issue by tpluscode** [HydraCG/Specifications#193]
I notice that hydra:Link is defined as a Property. 

I does not make sense that a link triple has a literal object. I think that `hydra:Link` should be changed so that it's an `ObjectProperty`.

**Comment by alien-mcl** [comment]
There are no terms in hydra's RDF representation that are using OWL (excluding the ontology itself).
I don't see any benefits from using `owl:ObjectProperty`.  Still, we could add a `@type: "@id"` to the hydra's [context](http://www.w3.org/ns/hydra/context.jsonld) that can be referenced by other - it should work fine for JSON-LD

**Comment by angelo-v** [comment]
I am with @alien-mcl Let's not introduce OWL if it's not there yet. I do not see us gaining much using this here.

I do not understand where you would put `@type: "@id"`?

**Comment by tpluscode** [comment]
Ok, thanks guys. I forgot that those terms are not RDFS. 

About `"@type": "@id"`, it will help simplify JSON structure but if the server is using other serialisation format then it does not shield them from pushing literal accidentally where a URI is expected.

FYI, I created hypermedia-app/hydra-validator#8 to add this to the analyser.
