### ISSUE TITLE
Ideas for additional features/vocabularies

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#20]
- [ ] Allow the documentation of sample requests/responses, can be used to build mock services and to improve documentation. This should probably not be part of the core vocabulary.
- [ ] Create separate vocabulary for CRUD applications
- [ ] More advanced querying

**Comment by alien-mcl** [comment]
Due to lack of activity in this issue, I'd like to close it. Still, whole this GitHub repo is a great place for suggesting features!
