### ISSUE TITLE
JSON-LD context missing @type

### ISSUE THREAD

**Issue by thewilkybarkid** [HydraCG/Specifications#201]
The JSON-LD context doesn't contain a `@type` for `hydra:manages`, `hydra:subject`, and `hydra:object`.

Refs https://gitlab.com/vincenttunru/rdf-namespaces/merge_requests/3.

**Comment by alien-mcl** [comment]
Indeed, it seems that `hydra:manages` does not have any `@type` defined. We may add it, but honestly - I don't expect other than blank nodes here (you'll end up with JSON object in this case).

As for the `hydra:subject` and `hydra:object` there is a `@type` = `@vocab` defined effectively making values of those predicates nodes with Iri expanded relatively to vocabulary.

**Comment by alien-mcl** [comment]
@thewilkybarkid - are these answers satisfactory for you? Can I close this issue?

**Comment by alien-mcl** [comment]
I assume answer satisfies @thewilkybarkid . If not, please feel free to reopen.
