### ISSUE TITLE
State more explicitely that hydra:return etc. are just hints

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#21]
See http://lists.w3.org/Archives/Public/public-hydra/2013Dec/0014.html and http://lists.w3.org/Archives/Public/public-hydra/2013Dec/0015.html for more information.

**Comment by alien-mcl** [comment]
I think this is covered in the spec now (section 4.2 Documenting a Web API):

>Keep in mind that operations specified in an ApiDocumentation may fail at runtime as either resources or the ApiDocumentation itself have changed since they have been retrieved. Also operation details like returns or possibleStatus may vary at runtime, which means client SHOULD verify received payloads at runtime.

How do you feel about it?

**Comment by alien-mcl** [comment]
OK - I'm closing it. It may happen that the snipped provided in my previous post may change it's location in the spec, still I feel topic of this issue is covered. Closing
