### ISSUE TITLE
Use writable instead of writeable?

### ISSUE THREAD

**Issue by dunglas** [HydraCG/Specifications#211]
## Description

Hydra use the spelling `writeable`, which seems less common than `writable` and error prone.

For instance [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) and [Ruby](https://ruby-doc.org/core-2.5.0/File.html#method-c-world_writable-3F) use `writable` without an `e`. Shouldn't this be changed?

**Comment by tpluscode** [comment]
I admit, this tripped me more than once too.

I don't think we would immediately remove the misspelled version but deprecate for now and keep two synonyms.

Would you find this acceptable or more confusing still?

**Comment by alien-mcl** [comment]
Yep - it indeed annoys me when spell-checker raises warnings.

I don't think we could replace it any time soon. As @tpluscode pointed, we could create another term with sameAs to the oldone and make the old one obsolete

**Comment by alien-mcl** [comment]
PR #219 covers this issue - closing
