### ISSUE TITLE
Allow returns/expects to be expressed in terms of a media type; what about multiple types?

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#22]
This is, e.g., necessary for things such as images. It is also necessary to define how multiple types in `expects`/`returns` should be interpreted. Do requests/responses need to be instances of _all_ classes or just of at least one?

**Comment by vanthome** [comment]
schema.org has for its `hydra:expects` counterpart corresponding properties for media types of the input and output `schema:encodingType` and `schema:contentType`. 
One could define multiple operations, one per type, if the content types would differ per `@type`.
At lease for the input part I think there should be a corresponding concept in hydra.
For the output it can make sense for documentation purposes (we had a similar discussion already I remember).

**Comment by alien-mcl** [comment]
This should be covered by the PR #186 - closing
