### ISSUE TITLE
Permalink for error.jsonld context

### ISSUE THREAD

**Issue by tpluscode** [HydraCG/Specifications#225]
## Description

@lanthaler, since #218 has been merged we now have a context document which can be used by API authors to extend problem+json document with RDF semantics

This appears to be available as http://www.markus-lanthaler.com/hydra/error 

What would it take to also have a redirect from, say, http://www.w3.org/ns/hydra/error.jsonld analogous to `context.jsonld`?

**Comment by tpluscode** [comment]
Oh wait, I did not check but the URL in the spec actually works 

```
http://www.w3.org/ns/hydra/error
```

Without `.jsonld` 👌

**Comment by lanthaler** [comment]
Yep, I set that up as you asked me to :-)

**Comment by tpluscode** [comment]
@lanthaler the `/hydra/error` resource is longer live. Why does is 404 now? Could you fix that?

**Comment by lanthaler** [comment]
Thanks for letting me know. I just fixed it

**Comment by tpluscode** [comment]
Great. Thanks
