### ISSUE TITLE
Replace property possibleStatus by statusCode in example 27.

### ISSUE THREAD

**Issue by cKlee** [HydraCG/Specifications#231]
## Description

Replace property possibleStatus by statusCode in example 27.

## More details

Property possibleStatus has range hydra:Status. Example shows an integer value. Matching property must be statusCode. See https://github.com/HydraCG/Specifications/pull/230

**Comment by alien-mcl** [comment]
This should be resolved by PR #230 - closing

**Comment by cKlee** [comment]
So I raised this issue wrongfully?

**Comment by alien-mcl** [comment]
I've been misunderstood - this issue is resolved with pull request #230 you've placed :)
