### ISSUE TITLE
Should properties and types that only differ in their capitalization be avoided?

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#28]
If the properties are changed to singular, even more properties will differ from their ranges only in their capitalization:

```
hydra:apiDocumentation -> hydra:ApiDocumentation

hydra:operation -> hydra:Operation
hydra:supportedProperty -> hydra:SupportedProperty
```

Do we want to avoid that (as Schema.org does for example)?

**Comment by alien-mcl** [comment]
This seems to be resolved with no further actions required. I believe changing names of core elements after several years would do more harm than good. I think it's OK to close it without any changes in the spec.
