### ISSUE TITLE
Define "priority of constituencies"

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#38]
Perhaps something similar to the "priority of constituencies" as defined by the HTML WG:

> In case of conflict, consider users over authors over implementors over specifiers over theoretical purity. In other words costs or difficulties to the user should be given more weight than costs to authors; which in turn should be given more weight than costs to implementors; which should be given more weight than costs to authors of the spec itself, which should be given more weight than those proposing changes for theoretical reasons alone. Of course, it is preferred to make things better for multiple constituencies at once."

http://www.w3.org/TR/html-design-principles/#priority-of-constituencies

**Comment by alien-mcl** [comment]
Due to lack of activity in this issue, I think it's OK to close it.
