### ISSUE TITLE
Document how "errors" can be given an identifier and be reused in responses

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#39]
Errors or possible statuses in general can be given an identifier that can then be directly reused in responses. According to [RubenVerborgh this should be documented in the spec](http://lists.w3.org/Archives/Public/public-hydra/2014Mar/0004.html):

> > > But doesn't really help anyway. Clients won't do anything with the
> > > description.
> > 
> > That might not be entirely true as you could give that specific status an
> > identifier and then return it as is as response:
> > 
> > ```
> >   {
> >     "@context": "http://www.w3.org/ns/hydra/context.jsonld",
> >     "@id": "http://example.com/api/errors/180984",
> >     "@type": "Status",
> >     "title": "Too Many Requests",
> >     "description": "A maximum of 500 requests per hour and user is allowed."
> >    }
> > ```
> 
> I like that very much.
> So much that I would actually recommend in the spec
> that the status is given an identifier, that it's not just a blank node.
> That way, it can be annotated easily later on.

**Comment by asbjornu** [comment]
How does this relate to [`application/problem+json`](https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-01)? Wouldn't it be wise to at least use the same properties and perhaps reference it as the recommended format for all error responses in the API?

**Comment by dret** [comment]
for the record: problem reports now have RFC status: http://tools.ietf.org/html/rfc7807

**Comment by alien-mcl** [comment]
Would it be OK to start a separate issue related to application/problem+json and close this one that is already resolved?

**Comment by asbjornu** [comment]
I'd prefer if a new issue was opened before this one is closed, but otherwise that's fine by me.
