### ISSUE TITLE
Improve definition of hydra:search

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#51]
**_This was [discussed on the mailing list](http://lists.w3.org/Archives/Public/public-hydra/2014Jun/0116.html):**_

> > > It's currently defined as "A IRI template that can be
> > > used to query a collection" (note a typo: "A_n_ IRI"), which hints
> > > that it's rdfs:domain is hydra:Collection. This is not captured
> > > explicitly in the RDF description of Hydra.
> > 
> > Yeah, that's true. But I think we should rather fix the description and not the domain. Or we use schema:domainIncludes (probably better). hydra:search isn't very well defined at the moment.
> 
> I think I'd prefer using schema:domainIncludes (because of its
> intended owl:unionOf-like semantics). When you say that we should fix
> the description of hydra:search, do you mean that it should be
> broadened to not only hint to hydra:Collection?

**Comment by alien-mcl** [comment]
I believe this has something to do with #48 - let's close it so we don';t have duplicates.
