### ISSUE TITLE
Is the term ApiDocumentation misleading

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#61]
There are concerns the term `ApiDocumentation` is misleading because it might be interpreted as being completely static. This could be solved either by highlighting the fact that this isn't the case in the spec or by renaming `ApiDocumentation` to something else.

See also the discussions on the mailing list: http://lists.w3.org/Archives/Public/public-hydra/2014Jul/0041.html

**Comment by tkawa** [comment]
I agree :+1:

**Comment by asbjornu** [comment]
Isn't the [`describedby` link relation](http://www.w3.org/TR/powder-dr/#appD) a good fit, making the `ApiDocumentation` concept superfluous?

**Comment by alien-mcl** [comment]
This should becovered by #223. Closing
