### ISSUE TITLE
Describe entry point -> ApiDocumentation flow

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#69]
**_[Martijn Faassen raised this](http://lists.w3.org/Archives/Public/public-hydra/2014Sep/0025.html):**_

> I'd like to see the use case described where the entry point comes
> first, it points to the Hydra docs, and the Hydra docs doesn't have to
> specify an entry point. And then secondarily describe the use case you
> have now where the entry point is embedded in the Hydra content

**Comment by asbjornu** [comment]
Will a `<link rel="describedby" href="/api/">` (in HTML) or `Link: </api/>; rel=describedby` (HTTP header) do?

**Comment by asbjornu** [comment]
This is related to #68, no?
