### ISSUE TITLE
Description of workflows

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#70]
Sometimes, it is necessary to execute a complete workflow in order to achieve a certain goal because the server and the client need to collaborate. It would be interesting to evaluate whether this is something that should be included into the Hydra Core vocabulary.

This was triggered by a question from Kev Kirkland (see http://lists.w3.org/Archives/Public/public-hydra/2014Sep/0039.html)

**Comment by alien-mcl** [comment]
This feels to be a little out of hydra scope. Also our further work might bring some generic features that might enable implementers to provide such a behavior - let's close it.
