### ISSUE TITLE
Add support for examples (Operations, IriTemplates, etc.)

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Specifications#74]
Often an example is much more helpful than a precise description of how something should look like.

See also http://lists.w3.org/Archives/Public/public-hydra/2014Oct/0041.html

**Comment by alien-mcl** [comment]
There are some examples and use cases available [here](https://github.com/HydraCG/Specifications/tree/master/drafts/use-cases). Also a #147 might bring some more details in future - closing.
