### ISSUE TITLE
Naming style: camelCase or not? Plural or not?

### ISSUE THREAD

**Issue by dunglas** [HydraCG/Specifications#81]
Hi,

I'm working on implementing a JSON-LD+Hydra API. Some property's names follow the camelCase style and some other are all in lowercase.

Ex:
* `entrypoint` / `readonly` / `writeonly` (all in small caps)
* `statusCodes` / `supportedProperty` / `supportedOperation` (cameCase)

A similar naming inconsistency appends with the plural form:
* `supportedClass` / `supportedOperation` (singular)
* `statusCodes` (plural)

Is it intended?

**Comment by RubenVerborgh** [comment]
Hi @dunglas, thanks for nothing this. Let's have the actual discussions on public-hydra@w3.org and use GitHub for issue status tracking. I [forwarded your mail](http://lists.w3.org/Archives/Public/public-hydra/2015Jan/0010.html).

**Comment by RubenVerborgh** [comment]
This issue seems to be resolved by #14 and #27, which are implemented by #84 and #85.

**Comment by lanthaler** [comment]
Hi Kévin,

> Some property's names follow the camelCase style and some other are all in lowercase.
> Ex:
> • entrypoint / readonly / writeonly (all in small caps)
> • statusCodes / supportedProperty / supportedOperation 

Entrypoint is debatable.. readonly and writeonly will be replaced with readable and writable, see issue #14.

> A similar naming inconsistency appends with the plural form:
> • supportedClass / supportedOperation (singular)
> • statusCodes (plural)
> Is it intended?

No, statusCodes will be dropped. See issue #27

So, summarized, this is mostly due to a currently outdated spec.
