### ISSUE TITLE
`void:triples` redefined to be an estimate

### ISSUE THREAD

**Issue by akuckartz** [HydraCG/Specifications#89]
According to http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/ the object of the property `void:triples` is
> an integer literal expressing the estimated total number of matching triples"

But http://www.w3.org/TR/void/ states:
> The total number of triples contained in the dataset

And that document states for `void:documents`:
> This property is intended for datasets where the total number of triples or entities is hard to determine. void:triples or void:entities should be preferred where practical.

That seems to substantiate that `void:triples` was intended for precise numbers, not estimates.

In October 2014 there was a mail thread where a different opinion was presented:

totalItems vs void:triples
[mail thread]
http://lists.w3.org/Archives/Public/public-hydra/2014Oct/0048.html

I think it would be better to define and use a new property `hydra:estimatedTiples` or `hydra:triplesEstimate`. Maybe that property can be defined as a super-property of `void:triples`.

**Comment by RubenVerborgh** [comment]
I [replied on-list](http://lists.w3.org/Archives/Public/public-hydra/2015Jan/0044.html).

**Comment by akuckartz** [comment]
Yes, I agree. Sorry for not having read that paragraph in the VoID specification. I only had searched for the property name in it :-(

But that illustrates that it can help to be a bit more verbose in the documentation of a property so that it can stand for itself - especially when a term ("total number") is not used according to the usual semantics ! Maybe that can be considered for a future version of the VoID specification.
