### ISSUE TITLE
How to suggest dereferenceability?

### ISSUE THREAD

**Issue by RubenVerborgh** [HydraCG/Specifications#91]
**How can a server suggest to a client that a certain resource can/should be dereferenced?**

_[Mailing list thread](http://lists.w3.org/Archives/Public/public-hydra/2015Jan/0167.html)_

The goal is not to find out whether they are dereferenceable or not, but whether it is worth (from the publishers' point of view) to follow them.

**Comment by RubenVerborgh** [comment]
### Solution 1: mark the resource as `hydra:Resource`

#### Example
```
<ResourceA> a hydra:Resource.
```

#### Advantages
- easy to express, it's just a type annotation

#### Disadvantages
- It might be incorrect to express this as a type, since dereferenceability is not an ontological concern.
- It is not possible to indicate that the server does _not_ expect the client to reference something.
- Conflict with the current definition of `hydra:Resource`. (See #90.)
- The party expressing referenceability (which server) is not explicitly mentioned.

**Comment by RubenVerborgh** [comment]
### Solution 2: indicate it through a `hydra:dereferenceable` property

#### Example
```
<ResourceA> hydra:dereferenceable true.
<ResourceB> hydra:dereferenceable false.
```

#### Advantages
- easy to express, it's just a property
- possible to indicate whether the server _does_ or _does not_ suggest dereferencing

#### Disadvantages
- The party expressing referenceability (which server) is not explicitly mentioned.

**Comment by kjetilk** [comment]
Sorry, I didn't read the thread, but the old-school way of doing this is using rdfs:seeAlso. I don't know if that gives the precision you want though.

**Comment by jaw111** [comment]
@kjetilk wouldn't that require that every property used to refer to something that dereferences would need to the rdfs:subPropertyOf rdfs:seeAlso? Either that or materialize the rdfs:seeAlso statements in every response.

Furthermore I'm going to be a pedant (sorry).

1. What do we mean by "dereferenceable", that the server gives *some* HTTP response, or something more specific like a HTTP 200 OK?
2. Is being dereferenceable a characteristic (I hesitate to say "property" as that's a somewhat loaded term) of the URI or the resource that URI identifies? For example what if I extend the example above with statement `<ResourceA> owl:sameAs <ResourceB>` where one of the URIs dereferences and the other does not.

**Comment by RubenVerborgh** [comment]
@kjetilk / @jaw111 Thanks for the feedback, please remember to have the discussions on the mailing list. I've added [your](http://lists.w3.org/Archives/Public/public-hydra/2015Jan/0168.html) [messages](http://lists.w3.org/Archives/Public/public-hydra/2015Jan/0169.html) there.

**Comment by alien-mcl** [comment]
This seems to be out of scope of hydra. Also there was no other activity since 2015, so I believe it's OK to close it.
