### ISSUE TITLE
The TPF spec should recommend paging

### ISSUE THREAD

**Issue by RubenVerborgh** [HydraCG/Specifications#92]
To avoid clients receiving huge responses upon simple queries (especially when requesting the "select all" fragment simply for its hypermedia controls), the spec should recommend paging.

Raised by @kasei on the [mailing list](http://lists.w3.org/Archives/Public/public-hydra/2015Jan/0184.html).

**Comment by elf-pavlik** [comment]
What do you think about approach described in Linked Data Platform Paging spec?
http://www.w3.org/TR/ldp-paging/

**Comment by RubenVerborgh** [comment]
http://lists.w3.org/Archives/Public/public-hydra/2015Feb/0048.html :wink:

**Comment by akuckartz** [comment]
See also #5 ;-)

**Comment by kasei** [comment]
Thanks!

**Comment by RubenVerborgh** [comment]
Thank you for bringing this up, @kasei. Made me realize how crucial paging is!
