### ISSUE TITLE
Clarify the reuse of the request URL inside of the fragment

### ISSUE THREAD

**Issue by RubenVerborgh** [HydraCG/Specifications#93]
The current example in the TPF spec with `?page=3&s=a` is confusing and too complicated for what we want to express. Also, it should perhaps account for the `Location` header.

Raised by @kasei on the [mailing list](http://lists.w3.org/Archives/Public/public-hydra/2015Jan/0184.html).

**Comment by alien-mcl** [comment]
This seems to be out of scope of hydra. Also there was no other activity in this issue since 2015 - closing.
