### ISSUE TITLE
Rename "@id" to "id" ?

### ISSUE THREAD

**Issue by akuckartz** [HydraCG/Specifications#95]
This was suggested by @msporny in https://github.com/json-ld/json-ld.org/pull/380#issuecomment-71382239 and https://github.com/json-ld/json-ld.org/pull/380#issuecomment-71392999

The other "@"-properties would be renamed as well.

(Sorry, I can not send that to the mailing list at the moment.)

**Comment by gkellogg** [comment]
For an application, aliasing `@id` to `id` can be a good idea, but for a generic library, probably not. The Hydra context may be used in a number of places where always aliasing keywords could create problems. It should be up to the developer integrating Hydra with other vocabularies to determine if keywords should be aliased.

**Comment by lanthaler** [comment]
I agree with Gregg and would add that this is out of scope for Hydra. I’ll thus close this issue. Feel free to reopen it if you think this really needs more discussion (which should then happen on the mailing list).
