### ISSUE TITLE
Add picture to LDF/TPF specs

### ISSUE THREAD

**Issue by RubenVerborgh** [HydraCG/Specifications#98]
by Nathan Ridley on the mailing list:

> If I may offer feedback on the specification, a picture speaks a thousand words. Some kind of diagram, or simple example architecture illustrating how LDF is supposed to work from a client-server perspective, would go a long way toward facilitating a better understanding of the LDF concept.

**Comment by akuckartz** [comment]
:+1:

**Comment by alien-mcl** [comment]
This is out of hydra scope - closing it.
