### ISSUE TITLE
Add support for describing headers accepted in supported operations 

### ISSUE THREAD

**Issue by nandana** [HydraCG/Specifications#99]
Some web applications (e.g., LDP apps) make use of HTTP headers such as Slug, Prefer for certain operations. It would help the client if this support can be explicitly described in the API documentation.  Further, it may be useful if the server can describe the range of the header, i.e., the values the server is willing to accept using  a template, a regex pattern, or an enumeration of values it will help the client to formulate a valid request. 

The initial discussion on Hydra mailing list is [here](https://lists.w3.org/Archives/Public/public-hydra/2015Mar/0013.html)

**Comment by alien-mcl** [comment]
@nadndana, we've just added some terms in PR #185 that should enable you to express header expectations. We've decided not to go into complex mechanism with templates.
If it still is your requirement feel free to reopen it.
